FROM node:4.4.3-wheezy

# Sails setup
WORKDIR /app/
ADD package.json /app/
ADD Gruntfile.js /app/
RUN npm install npm -g && npm install -g sails && npm install
ADD . .

VOLUME ["/app/api", "/app/assets", "/app/config", "app/tasks", "app/views"]

EXPOSE 1337

CMD ["sails","lift", "--models.migrate=create", "--verbose"]

