FROM node:4.4.3-wheezy

# Sails setup
WORKDIR /app/
ADD package.json /app/
ADD Gruntfile.js /app/
RUN npm install -g sails && npm install
ADD . .

VOLUME /app

EXPOSE 1337

#ENV NODE_ENV=production

CMD ["sails","lift", "--models.migrate=create", "--verbose"]

